application: hack-for-japan
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(html|css|js|jpg|gif|png))
  static_files: static/\1
  upload: static/(.*\.(html|css|js|jpg|gif|png))

- url: /.*
  script: helloworld.py
